### PR TITLE
Add read_salm()

### PR DESCRIPTION
**Pull request by awhug**
Adds functionality to import Small Area Labour Market (SALM) data. I've added basic documentation and an example to the README.

There's a few dependencies added here - in particular I'm using `httr2` for web requests which is now recommended over the original `httr`, and `rvest` to identify relevant files on the JSA SALM page. I like the clear formatting of `rlang::arg_match`, so this is a dependency too, but not essential to make this work and could probably be replaced with a base `match.arg`.

Note that I have suppressed the IVI figure in the README being rendered until the URL error is resolved. I've got a PR ready to solve this in #2. When it is, you'd just need to drop the `eval = FALSE`.

### CODE REVIEW

**Comment by MattCowgill** [comment]
At a glance I'm not sure why this one is failing - I'll have a look when I can (likely later this week). Thanks again

**Comment by awhug** [comment]
Yep, this one is puzzling me too. 

A fresh clone of the repo and install of the package from this branch has `read_salm` running fine on my work Windows 10. Tested on Linux at home too without issue, so not sure what's wrong.

Will also see if I can figure out the problem and update this week.

**Comment by MattCowgill** [comment]
I tested in a Linux VM and it worked fine. I'll puzzle through this, I wonder if I've done something wrong in setting up the Actions

**Comment by awhug** [comment]
Tried adding a line that disables HTTP/2 in favour of HTTP/1.1. Doesn't seem to impact performance on my end and might be a workaround. Give it a rip? 

Edit: Well that ain't it

**Comment by MattCowgill** [comment]
Hey sorry for the radio silence @awhug, thanks again for your work on this. All I can think is maybe there's some issue with the way I've set up the GH Actions... I'll try to puzzle through this one this week

**Comment by hamgamb** [comment]
Hey Matt.  I used to run a GH Action to scrape JSA data this way but ran into the same issues as you. It would work fine locally but never (or rarely) work when running the action. I never solved it and switched to the method you're using now of guessing the URL! Cold comfort perhaps?

**Comment by MattCowgill** [comment]
I'm gonna merge this as-is. It works locally. I think that JSA must be blocking GHA from scraping its site, maybe?

**Comment by MattCowgill** [comment]
Thanks again @awhug

**Pull request merged**
